config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'
  post 'sales', to: 'sales#create'
  get 'sales/done', to: 'sales#done'

  root 'sales#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :cod, uniqueness: true
  validates :detail, presence: true
  validates :category, inclusion:  {in: %w(uno dos tres cuatro cinco)}
  validates :value, numericality: { only_integer: true, greater_than: 0}
  validates :discount, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 40}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
    @sale = Sale.new
  end

  def create
   @sale = Sale.new(sale_params)
   @sale.total = @sale.value - (@sale.value/100*@sale.discount)
   if @sale.tax == false
     @sale.total *= 1.19
     @sale.tax = 19
   else
     @sale.tax = 0
   end
   @sale.save
   redirect_to sales_done_path #esta OK
  end


  def done
    @sales = Sale.all
  end

  private
  def sale_params
    params.require(:sale).permit(:cod, :detail, :category, :value, :discount, :tax)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Registroventas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/done.html.erb
<h1>El registro fue almacenado con éxito!</h1>

<% @sales.each do |s| %>
  <p>Cod: <%= s.cod %></p>
  <p>Detail: <%= s.detail %></p>
  <p>Category: <%= s.category %></p>
  <p> Value: <%= s.value %></p>
  <p>Discount: <%= s.discount %></p>
  <p>Tax: <%= s.tax %></p>
  <p>Total: <%= s.total %></p>
<% end %>

</div><%= link_to 'Volver', sales_new_path, class:'btn btn-warning'%>

app/views/sales/new.html.erb
<h1>Sales#new</h1>

<%= form_with model: @sale, local: true do |form| %>
 <p><%= form.label :cod %></p>
 <p><%= form.number_field :cod, id: :cod %></p>

 <%= form.label :detail %></p>
 <p><%= form.text_area :detail, id: :detail %></p>

 <p><%= form.label :category %></p>
 <p><%= form.text_field :category, id: :category %></p>


 <p><%= form.label :value %></p>
 <p><%= form.number_field :value, id: :value %></p>

 <p><%= form.label :discount %></p>
 <p><%= form.number_field :discount, id: :discount %></p>

 <p><%= form.label :tax, "Exento de IVA" %></p>
 <p><%= form.check_box :tax, id: :tax %></p>

 <p><%= form.submit "Crear" %>

<% end %>